### ISSUE TITLE
Question: Use FlakyTest via dotnet test command line?

### ISSUE THREAD

**Issue by rgustavsson** [Kritner-Blogs/FlakyTest.XUnit#21]
Hey!

Here's a simple question :)

I tried out using FlakyFact when debugging in Visual Studio and all felt good.

Now that I try to run the tests via command line, e.g. `dotnet test`, then the FlakyTest parts aren't taken into consideration.
Am I doing something wrong or should this not be possible?

**Comment by Kritner** [comment]
Hey @rgustavsson could you elaborate on "not working"?  How are you determining they aren't working?  

FWIW the github actions running for the repo is *all* CLI based, and you can see in the build logs that the `FlakyFact` attributes are being reattempted.

One example: https://github.com/Kritner-Blogs/FlakyTest.XUnit/actions/runs/4039288571/jobs/6943875444

![image](https://user-images.githubusercontent.com/8814983/233073635-c9b268a0-50c3-43d0-96d7-a0c71b99f8ed.png)

**Comment by Kritner** [comment]
Oh one additional thought - https://github.com/Kritner-Blogs/FlakyTest.XUnit/blob/main/test/FlakyTest.XUnit.Tests/xunit.runner.json if you use a similar `xunit.runner.json` (specifically the `diagnosticMessages`) you should be able to see in the `dotnet test` output the outcomes of the retries (or not if retries aren't needed, or in your case of potentially not working)

**Comment by rgustavsson** [comment]
I'm sorry @Kritner 
Seem like I'm doing it wrong and that it actually works.
